### PR TITLE
Update alpha function for general application

### PR DESCRIPTION
**Pull request by milescb**
I propose a change to the function alpha which will work with any equations, F. In the current case, alpha only works when a single, multivariable function is provided. My implementation is consistent with the above definition of alpha, although is more complex.

### CODE REVIEW

**Comment by PBrdng** [comment]
I agree that this alpha is the general definition. For hypersurfaces (`n=N-1`), however, I think it is not efficient, because `qr` computes the full QR-decomposition (normal space AND tangent space). Maybe, one could put a comment that in the general situation one would use your alpha (in fact, in the paper we use code for alpha that is like yours).

**Comment by saschatimme** [comment]
Assuming people just copy example code, I would suggest to go with the more general solution :)

**Comment by milescb** [comment]
I agree with @saschatimme. I certainly first just copied and was confused when it didn't work. That being said, @PBrdng's solution for hypersurfaces is definitely at least slightly faster and a very clever simplification. Maybe adding a comment with the general solution as @PBrdng suggested would be the best solution?

**Comment by PBrdng** [comment]
Valid point. Okay, let's integrate @lvb5 's code!

**Pull request merged**
